MCU = atmega32u4

BOOTLOADER = caterina

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no

RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
SPLIT_KEYBOARD = yes
